### PR TITLE
Change the type of a record

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @vjovanov @cvogt

**Comment by vjovanov** [comment]
The code looks good! I will scrutinise (benchmarks, IDE tests, etc.) this PR after April 2nd. Please do not release it until then. We need to do a spring cleaning on this project anyhow. 

Merge after fixing the type error.

**Comment by cvogt** [comment]
@densh yeah, the defs... :).

@gzm0 I'll give this another post mortem review when I recovered some sleep.

**Comment by densh** [comment]
The README seems to be out of date. It still says that records types can not be explicitly mentioned.

**Pull request merged**
