### PR TITLE
Bumps the scala.js version.

### PR DESCRIPTION
**Pull request by vjovanov**
Review by @gzm0

### CODE REVIEW

**Comment by vjovanov** [comment]
After the review let me know if I should be in charge of doing the releases.

**Comment by gzm0** [comment]
LGTM. Consider changing the commit message to: "Bump Scala and Scala.js versions."

**Comment by gzm0** [comment]
Feel free to release a new version once this is in. (Will also bring the new syntax for types).

**Comment by vjovanov** [comment]
OK. Thanks!

**Pull request merged**
